### PR TITLE
Added a system for base excitation problems.

### PR DESCRIPTION
**Pull request by moorepants**
- [x] Add in the animation we created last year.
- [ ] Maybe add the force/displacement transmisbility plots (but I think I'd rather them construct them from data)
- [x] There is no way to have the velocity of the "car" available in the plotting command. Maybe that needs to be a system constant.

### CODE REVIEW

**Comment by moorepants** [comment]
@ixjlyons @sixpearls What do you all think of these API choices for the base excitation system? I named the new methods `sinusoidal_base_displacing_response` and `periodic_displacing_response` to stay consistent with the super class, but since this is a one off system it probably isn't that big of a deal what the names are.

**Comment by moorepants** [comment]
It may be better to have them add the forcing parameters like:

```
sys.constants['forcing_amplitude'] = 5.0
sys.constants['forcing_frequency'] = 3.0
```

This way this information is available internally to the class. Then you can imagine writing input functions in the same vien as the measurements, mck coefff function, plot, etc:

**Comment by ixjlyons** [comment]
I could go either way on having constants for input displacement amplitude and frequency.

I did think of something though: one thing we're trying to do is look at real systems, whereas this class is fairly generic. Does it make sense to add a `QuarterCarSystem` or something that just defines the constants and maybe has a few convenience functions for forward speed etc.? Something like the `ClockPendulumSystem`. This actually brings up a few other ideas that would probably involve breaking changes. I'll make an issue.

**Comment by moorepants** [comment]
I actually created a "car" system this morning to do that same thing. I'll push in a few.

**Pull request merged**
