### PR TITLE
Periodic forcing bug

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
Ok this test does a pretty good job covering the base excitation system. I think all the code I wrote is correct (at least for an and bn where n =1). I didn't change the code beside move things around. So I still don't know why I can't compute force transmissibilty and phase angles. The code must be incorrect in the notebooks...

**Comment by ixjlyons** [comment]
I audited the periodic forcing and base excitation stuff pretty thoroughly yesterday and didn't find any issues.

One mistake I was making on the quarter car force transmissibility was I wasn't setting the travel speed (or alternatively the bump distance) to match the excitation frequency so the frequency calculated in the force measurement function was correct. Here's a working example that's as clean as I can make it so there are no global variables or anything to make this mistake:

```python
from resonance.linear_systems import SimpleQuarterCarSystem
import numpy as np
import matplotlib.pyplot as plt


def force_on_car(suspension_damping, suspension_stiffness,
                 car_vertical_position, car_vertical_velocity, travel_speed,
                 bump_dist, bump_height, time):
    wb = travel_speed / bump_dist * 2 * np.pi
    y = bump_height * np.sin(wb * time)
    yd = bump_height * wb * np.cos(wb * time)
    return (suspension_damping * (car_vertical_velocity - yd) +
            suspension_stiffness * (car_vertical_position - y))


sys = SimpleQuarterCarSystem()
sys.constants['bump_dist'] = 6
sys.constants['bump_height'] = 0.01
sys.add_measurement('force_on_car', force_on_car)

frequencies = np.linspace(1.0, 20.0, num=100)
amplitudes = np.zeros(*frequencies.shape)
for i, wb in enumerate(frequencies):
    sys.constants['travel_speed'] = wb * sys.constants['bump_dist'] / 2 / np.pi
    traj = sys.sinusoidal_base_displacing_response(
        sys.constants['bump_height'], wb, 20)
    amplitudes[i] = np.max(traj[15:].force_on_car)

ft = amplitudes / sys.constants['suspension_stiffness'] / \
        sys.constants['bump_height']
plt.plot(frequencies, ft)
plt.show()
```

image

Haven't messed with phase yet. Could add a unit tests for `MassSpringDamperSystem` and `BaseExcitationSystem` to make sure the force/displacement transmissibility matches the analytic expression.

**Comment by moorepants** [comment]
Ah! yes. I think the way we did this in class and made measurements for wb was a better approach so you don't have to manually manage the relationship between v and wb. Thanks!! That looks great.

**Comment by moorepants** [comment]
Please add the tests. That would be great!

**Pull request merged**
